try:
    result =10/0
except Exception as e:
    print("Caught a general exception",e)